# Air live-reload configuration for renutri
root = "."
tmp_dir = "tmp"

[build]
  # Build the server binary
  cmd = "go build -o tmp/server ./cmd/server"
  bin = "tmp/server"
  include_ext = ["go", "sql", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "node_modules", "internal/db/migrations"]
  exclude_ext = ["swp", "tmp", "log"]
  delay = 1000
  stop_on_error = false

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
